spring:
  application:
    name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://89.104.68.220:5432/post_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASS:Psql7355}
    hikari:
      schema: post_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS post_schema
      connection-timeout: 10000
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://89.104.68.220:8761/eureka/}
    enabled: true