spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

app:
  feignClient:
    url: "http://localhost:8080"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
