spring:
  profiles:
    active: local
  application:
    name: post
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    enabled: true
  kafka:
    bootstrap-servers: 89.104.68.220:9094

app:
  kafka:
    notificationTopic: "notification-top"
    kafkaMessageGroupId: "kafka-message-group-id"
  auth:
    validate-url: "http://89.104.68.220:8081/api/v1/auth/getclaims"

eureka:
  instance:
    hostname: 89.104.68.220
  client:
    service-url:
      defaultZone: http://89.104.68.220:8761/eureka

server:
  port: 8080