package com.example.mcpost.model.enums;

public enum NotificationType {
    FRIEND_REQUEST, FRIEND_BIRTHDAY, FRIEND_APPROVE, FRIEND_BLOCKED, FRIEND_UNBLOCKED, FRIEND_SUBSCRIBE, USER_BIRTHDAY, LIKE, POST_COMMENT, COMMENT_COMMENT, POST, MESSAGE, SEND_EMAIL_MESSAGE
}
